### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by landoskape** [landoskape/networkAlignmentAnalysis#63]
I've just realized that the black linting check isn't doing anything. Guess I wrote that before I knew how to use github actions 🙃. 

It would be nice to actually use formatting to keep everything structured the same way. Do people agree / want this? 

I propose a few changes:

### Github Lint action:
Change ``options: --line-length 150`` to ``options: --check --diff`` so that the action actually uses black to check the formatting and print the difference. By not specifying any other options it'll use the pyproject.toml.
```yml
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --diff"
```

### Black formatting settings
Line-length 150 is a bit long, maybe a more standard length like 88? Not a big deal, just a thought.

### Format with black... 
I propose that we run `black .` on the codebase. We can do this in a single commit/push (PR if desired). To make sure the "blame" is correct, we can use the following steps:

1. Format the entire codebase with Black in a single commit
2. Create `.git-blame-ignore-revs` in the repo root and add the formatting commit hash:
   ```bash
   # Black formatting commits to ignore
   <commit-hash>  # Whatever the commit was
   ```
3. Configure git to use this file:
   ```bash
   git config blame.ignoreRevsFile .git-blame-ignore-revs
   ```

Note: New contributors will have to run this config after cloning, we can include a statement in the dev docs somewhere. 

### Additional option: 
We could set this up in a pre-commit hook so it happens automatically at commit time. If people are interested I'm happy to set that up.
